version: "3.2"
networks:
  my-network:
    ipam:
      driver: default
      config:
        - subnet: 172.16.0.0/16

services:
  nginx_web:
    container_name: nginx_web
    restart: always
    build:
      context: ./application
    networks:
      my-network:
        ipv4_address: 172.16.1.2
        aliases: 
          - nginx
    ports:
      - "8080:80"
    volumes:
      - type: bind
        source: ./logs
        target: /var/log/nginx/
  database:
    container_name: database
    image: mongo:latest
    restart: always
    environment: 
      - MONGO_INITDB_ROOT_USERNAME=${USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${PASSWORD}
      - MONGO_INITDB_DATABASE=${DATABASE}
    networks:
      my-network:
        ipv4_address: 172.16.1.3
        aliases: 
          - mongodb
    ports:
      - "27017:27017"
    volumes:
      - ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
    depends_on:
      - nginx_web
  script:
    container_name: script
    restart: always
    build:
      context: ./script
    networks:
      my-network:
        ipv4_address: 172.16.1.4
        aliases: 
          - script
    volumes:
      - type: bind
        source: ./logs
        target: /usr/src/app/
